print("Compara due differenti valori")
print("5 == 5")
print(5 == 5)
print("5 != 5")
print(5 != 5)
print("5 > 5")
print(5 > 5)
print("5 >= 5")
print(5 >= 5)
print("5 < 5")
print(5 < 5)
print("5 <= 5")
print(5 <= 5)
print("il risultato è sempre un booleano")